plugins {
    id 'java-gradle-plugin'
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation gradleTestKit()
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

gradlePlugin {
    plugins {
        gaUtils {
            id = 'dev.team_argentum.ga-utils'
            implementationClass = 'dev.team_argentum.ga_utils.gradle.GaUtilsPlugin'
        }
    }
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}
